// ─── APCA FONT MATRIX ────────────────────────────────────────────────────────
// Auto-generated by extract-apca-lut.js — do not edit manually.
// Source: node_modules/apca-w3/data/LUT-GseriesMay28-2022.js
// Last generated: 2026-04-10T06:11:18.723Z
//
// fontMatrixG: given an Lc value, returns minimum recommended font size (px)
// for each font weight. This is the same table used by apcacontrast.com.

export const fontMatrixG = {
  "0": {
    "100": 999,
    "200": 999,
    "300": 999,
    "400": 999,
    "500": 999,
    "600": 999,
    "700": 999,
    "800": 999,
    "900": 999
  },
  "10": {
    "100": 999,
    "200": 999,
    "300": 999,
    "400": 999,
    "500": 999,
    "600": 999,
    "700": 999,
    "800": 999,
    "900": 999
  },
  "15": {
    "100": 777,
    "200": 777,
    "300": 777,
    "400": 777,
    "500": 777,
    "600": 777,
    "700": 777,
    "800": 777,
    "900": 777
  },
  "20": {
    "100": 777,
    "200": 777,
    "300": 777,
    "400": 777,
    "500": 777,
    "600": 777,
    "700": 777,
    "800": 777,
    "900": 777
  },
  "25": {
    "100": 777,
    "200": 777,
    "300": 777,
    "400": 120,
    "500": 120,
    "600": 108,
    "700": 96,
    "800": 96,
    "900": 96
  },
  "30": {
    "100": 777,
    "200": 777,
    "300": 120,
    "400": 108,
    "500": 108,
    "600": 96,
    "700": 72,
    "800": 72,
    "900": 72
  },
  "35": {
    "100": 777,
    "200": 120,
    "300": 108,
    "400": 96,
    "500": 72,
    "600": 60,
    "700": 48,
    "800": 48,
    "900": 48
  },
  "40": {
    "100": 120,
    "200": 108,
    "300": 96,
    "400": 60,
    "500": 48,
    "600": 42,
    "700": 32,
    "800": 32,
    "900": 32
  },
  "45": {
    "100": 108,
    "200": 96,
    "300": 72,
    "400": 42,
    "500": 32,
    "600": 28,
    "700": 24,
    "800": 24,
    "900": 24
  },
  "50": {
    "100": 96,
    "200": 72,
    "300": 60,
    "400": 32,
    "500": 28,
    "600": 24,
    "700": 21,
    "800": 21,
    "900": 21
  },
  "55": {
    "100": 80,
    "200": 60,
    "300": 48,
    "400": 28,
    "500": 24,
    "600": 21,
    "700": 18,
    "800": 18,
    "900": 18
  },
  "60": {
    "100": 72,
    "200": 48,
    "300": 42,
    "400": 24,
    "500": 21,
    "600": 18,
    "700": 16,
    "800": 16,
    "900": 18
  },
  "65": {
    "100": 68,
    "200": 46,
    "300": 32,
    "400": 21.75,
    "500": 19,
    "600": 17,
    "700": 15,
    "800": 16,
    "900": 18
  },
  "70": {
    "100": 64,
    "200": 44,
    "300": 28,
    "400": 19.5,
    "500": 18,
    "600": 16,
    "700": 14.5,
    "800": 16,
    "900": 18
  },
  "75": {
    "100": 60,
    "200": 42,
    "300": 24,
    "400": 18,
    "500": 16,
    "600": 15,
    "700": 14,
    "800": 16,
    "900": 18
  },
  "80": {
    "100": 56,
    "200": 38.25,
    "300": 23,
    "400": 17.25,
    "500": 15.81,
    "600": 14.81,
    "700": 14,
    "800": 16,
    "900": 18
  },
  "85": {
    "100": 52,
    "200": 34.5,
    "300": 22,
    "400": 16.5,
    "500": 15.625,
    "600": 14.625,
    "700": 14,
    "800": 16,
    "900": 18
  },
  "90": {
    "100": 48,
    "200": 32,
    "300": 21,
    "400": 16,
    "500": 15.5,
    "600": 14.5,
    "700": 14,
    "800": 16,
    "900": 18
  },
  "95": {
    "100": 45,
    "200": 28,
    "300": 19.5,
    "400": 15.5,
    "500": 15,
    "600": 14,
    "700": 13.5,
    "800": 16,
    "900": 18
  },
  "100": {
    "100": 42,
    "200": 26.5,
    "300": 18.5,
    "400": 15,
    "500": 14.5,
    "600": 13.5,
    "700": 13,
    "800": 16,
    "900": 18
  },
  "105": {
    "100": 39,
    "200": 25,
    "300": 18,
    "400": 14.5,
    "500": 14,
    "600": 13,
    "700": 12,
    "800": 16,
    "900": 18
  },
  "110": {
    "100": 36,
    "200": 24,
    "300": 18,
    "400": 14,
    "500": 13,
    "600": 12,
    "700": 11,
    "800": 16,
    "900": 18
  },
  "115": {
    "100": 34.5,
    "200": 22.5,
    "300": 17.25,
    "400": 12.5,
    "500": 11.875,
    "600": 11.25,
    "700": 10.625,
    "800": 14.5,
    "900": 16.5
  },
  "120": {
    "100": 33,
    "200": 21,
    "300": 16.5,
    "400": 11,
    "500": 10.75,
    "600": 10.5,
    "700": 10.25,
    "800": 13,
    "900": 15
  },
  "125": {
    "100": 32,
    "200": 20,
    "300": 16,
    "400": 10,
    "500": 10,
    "600": 10,
    "700": 10,
    "800": 12,
    "900": 14
  }
};

export const fontMatrixLcKeys = [0,10,15,20,25,30,35,40,45,50,55,60,65,70,75,80,85,90,95,100,105,110,115,120,125];
export const fontMatrixWeightKeys = [100,200,300,400,500,600,700,800,900];

// Given an Lc value and weight, returns the minimum recommended font size in px.
// Interpolates between the two nearest Lc rows for sub-5-point precision.
export function minSizeForLc(lcValue, weightKey) {
  const keys = fontMatrixLcKeys;

  let lowerLc = null, upperLc = null;
  for (let i = 0; i < keys.length; i++) {
    if (keys[i] <= lcValue) lowerLc = keys[i];
    if (keys[i] >= lcValue && upperLc === null) upperLc = keys[i];
  }
  if (lowerLc === null) lowerLc = keys[0];
  if (upperLc === null) upperLc = keys[keys.length - 1];

  const wKeys = fontMatrixWeightKeys;
  let wLo = wKeys[0], wHi = wKeys[wKeys.length - 1];
  for (const w of wKeys) { if (w <= weightKey) wLo = w; }
  for (const w of wKeys) { if (w >= weightKey) { wHi = w; break; } }

  function interpWeight(lcRow, wTarget) {
    const row = fontMatrixG[lcRow];
    if (!row) return null;
    let lo = wLo, hi = wHi;
    while (lo >= wKeys[0] && row[lo] == null) lo -= 100;
    while (hi <= wKeys[wKeys.length-1] && row[hi] == null) hi += 100;
    const vLo = row[lo], vHi = row[hi];
    if (vLo == null && vHi == null) return null;
    if (vLo == null) return vHi;
    if (vHi == null) return vLo;
    if (lo === hi) return vLo;
    const t = (wTarget - lo) / (hi - lo);
    return vLo + t * (vHi - vLo);
  }

  const sizeAtLower = interpWeight(lowerLc, weightKey);
  const sizeAtUpper = interpWeight(upperLc, weightKey);

  if (sizeAtLower == null && sizeAtUpper == null) return null;
  if (sizeAtLower == null) return sizeAtUpper;
  if (sizeAtUpper == null) return sizeAtLower;
  if (lowerLc === upperLc) return sizeAtLower;

  const t = (lcValue - lowerLc) / (upperLc - lowerLc);
  return sizeAtLower + t * (sizeAtUpper - sizeAtLower);
}
